blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://docs.solace.com/
    about: For more documentation about PubSub+ platform and APIs
  - name: Community 
    url: https://solace.community/
    about: Ask the Solace community about anything Solace!
  - name: Support
    url: https://solace.com/support/
    about: Contact support if you have a paid support plan
